export const API_DOMAINS = [
  "auth",
  "catalog",
  "pos",
  "inventory",
  "indents",
  "cash",
  "accounting",
  "attendance",
  "staff",
  "notifications",
  "cron",
] as const

export type ApiDomain = (typeof API_DOMAINS)[number]

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE"

export type AuthPolicy =
  | "public-nextauth"
  | "session"
  | "admin"
  | "cron-secret"

export type ApiRouteDefinition = {
  id: string
  domain: ApiDomain
  path: string
  file: string
  methods: readonly HttpMethod[]
  auth: AuthPolicy
  owner: string
  summary: string
  reads: readonly string[]
  writes: readonly string[]
  risk: "low" | "medium" | "high"
  notes?: string
}

export const API_ROUTES = [
  {
    id: "auth.nextauth",
    domain: "auth",
    path: "/api/auth/[...nextauth]",
    file: "app/api/auth/[...nextauth]/route.ts",
    methods: ["GET", "POST"],
    auth: "public-nextauth",
    owner: "Authentication",
    summary: "NextAuth credentials endpoint for PIN login session creation and callback handling.",
    reads: ["User"],
    writes: ["NextAuth session cookies"],
    risk: "high",
    notes: "Do not change provider behavior without testing login and protected route access.",
  },
  {
    id: "products.collection",
    domain: "catalog",
    path: "/api/products",
    file: "app/api/products/route.ts",
    methods: ["GET", "POST"],
    auth: "session",
    owner: "Product catalog",
    summary: "Lists products with sizes, or creates a product with one or more sellable sizes.",
    reads: ["Product", "ProductSize"],
    writes: ["Product", "ProductSize"],
    risk: "high",
  },
  {
    id: "products.item",
    domain: "catalog",
    path: "/api/products/[id]",
    file: "app/api/products/[id]/route.ts",
    methods: ["PATCH", "DELETE"],
    auth: "admin",
    owner: "Product catalog",
    summary: "Updates product metadata and sizes, or deletes an unused product.",
    reads: ["Product", "ProductSize"],
    writes: ["Product", "ProductSize"],
    risk: "high",
  },
  {
    id: "products.barcode",
    domain: "catalog",
    path: "/api/products/[id]/barcode",
    file: "app/api/products/[id]/barcode/route.ts",
    methods: ["PATCH"],
    auth: "admin",
    owner: "Product catalog",
    summary: "Assigns or updates the barcode for a product size.",
    reads: ["ProductSize"],
    writes: ["ProductSize"],
    risk: "medium",
  },
  {
    id: "products.import",
    domain: "catalog",
    path: "/api/admin/products/import",
    file: "app/api/admin/products/import/route.ts",
    methods: ["POST"],
    auth: "admin",
    owner: "Product import",
    summary: "Imports products and sizes from an uploaded workbook.",
    reads: ["Uploaded workbook"],
    writes: ["Product", "ProductSize"],
    risk: "high",
    notes: "Large catalog changes should be tested against duplicate item codes and placeholder KSBCL codes.",
  },
  {
    id: "misc-items.collection",
    domain: "catalog",
    path: "/api/misc-items",
    file: "app/api/misc-items/route.ts",
    methods: ["GET", "POST"],
    auth: "admin",
    owner: "Misc sales",
    summary: "Lists misc items or creates a misc item used by POS.",
    reads: ["MiscItem"],
    writes: ["MiscItem"],
    risk: "high",
  },
  {
    id: "misc-items.item",
    domain: "catalog",
    path: "/api/misc-items/[id]",
    file: "app/api/misc-items/[id]/route.ts",
    methods: ["PATCH"],
    auth: "admin",
    owner: "Misc sales",
    summary: "Updates an existing misc item used by POS.",
    reads: ["MiscItem"],
    writes: ["MiscItem"],
    risk: "high",
  },
  {
    id: "misc-items.metrics",
    domain: "catalog",
    path: "/api/misc-items/metrics",
    file: "app/api/misc-items/metrics/route.ts",
    methods: ["GET"],
    auth: "admin",
    owner: "Misc sales",
    summary: "Summarizes misc sales revenue split for a date range.",
    reads: ["BillLine", "MiscItem", "Bill"],
    writes: [],
    risk: "medium",
  },
  {
    id: "expense-categories.collection",
    domain: "accounting",
    path: "/api/expense-categories",
    file: "app/api/expense-categories/route.ts",
    methods: ["GET", "POST"],
    auth: "session",
    owner: "Expenses",
    summary: "Lists expense categories or creates a new active category.",
    reads: ["ExpenseCategory"],
    writes: ["ExpenseCategory"],
    risk: "medium",
  },
  {
    id: "expenses.collection",
    domain: "accounting",
    path: "/api/expenses",
    file: "app/api/expenses/route.ts",
    methods: ["GET", "POST"],
    auth: "session",
    owner: "Expenses",
    summary: "Lists expenses for a date range or records a new expenditure.",
    reads: ["Expenditure", "ExpenseCategory"],
    writes: ["Expenditure", "GallaEvent"],
    risk: "high",
  },
  {
    id: "ledger.collection",
    domain: "accounting",
    path: "/api/ledger",
    file: "app/api/ledger/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "Ledger",
    summary: "Returns owner and cashier ledger rows for reporting.",
    reads: ["Bill", "BillLine", "MiscSale", "Expenditure"],
    writes: [],
    risk: "medium",
  },
  {
    id: "reports.third-party-payout",
    domain: "accounting",
    path: "/api/reports/third-party-payout",
    file: "app/api/reports/third-party-payout/route.ts",
    methods: ["GET"],
    auth: "admin",
    owner: "Supplier payouts",
    summary: "Summarizes third-party misc sales for supplier payout reporting.",
    reads: ["Bill", "BillLine", "MiscItem"],
    writes: [],
    risk: "medium",
  },
  {
    id: "galla.current",
    domain: "cash",
    path: "/api/galla",
    file: "app/api/galla/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "Cash control",
    summary: "Returns the galla day, cash events, and computed balance for a business date.",
    reads: ["GallaDay", "GallaEvent"],
    writes: [],
    risk: "medium",
  },
  {
    id: "galla.close",
    domain: "cash",
    path: "/api/galla/close",
    file: "app/api/galla/close/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "Cash control",
    summary: "Closes a galla day with counted cash and records the variance.",
    reads: ["GallaDay", "GallaEvent"],
    writes: ["GallaDay", "GallaEvent"],
    risk: "high",
  },
  {
    id: "pos.items",
    domain: "pos",
    path: "/api/pos/items",
    file: "app/api/pos/items/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "POS catalog",
    summary: "Returns all sellable liquor sizes and active misc items for the POS picker.",
    reads: [
      "InventorySession",
      "StockEntry",
      "ReceiptItem",
      "BillLine",
      "StockAdjustment",
      "ProductSize",
      "Product",
      "MiscItem",
    ],
    writes: [],
    risk: "medium",
  },
  {
    id: "pos.search",
    domain: "pos",
    path: "/api/pos/search",
    file: "app/api/pos/search/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "POS catalog",
    summary: "Searches liquor and misc items by name, item code, or barcode.",
    reads: ["ProductSize", "Product", "MiscItem"],
    writes: [],
    risk: "medium",
  },
  {
    id: "pos.barcode",
    domain: "pos",
    path: "/api/pos/barcode/[code]",
    file: "app/api/pos/barcode/[code]/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "POS scanning",
    summary: "Resolves a scanned barcode to either a liquor product size or misc item.",
    reads: ["ProductSize", "Product", "MiscItem"],
    writes: [],
    risk: "high",
  },
  {
    id: "pos.map-barcode",
    domain: "pos",
    path: "/api/pos/map-barcode",
    file: "app/api/pos/map-barcode/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "POS scanning",
    summary: "Maps an unknown barcode to an existing liquor size or misc item.",
    reads: ["ProductSize", "MiscItem"],
    writes: ["ProductSize", "MiscItem"],
    risk: "high",
  },
  {
    id: "pos.open-tabs",
    domain: "pos",
    path: "/api/pos/open-tabs",
    file: "app/api/pos/open-tabs/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "POS tabs",
    summary: "Lists pending open customer tabs that can be resumed or settled.",
    reads: ["Bill", "BillLine"],
    writes: [],
    risk: "medium",
  },
  {
    id: "pos.recent-bills",
    domain: "pos",
    path: "/api/pos/recent-bills",
    file: "app/api/pos/recent-bills/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "POS bills",
    summary: "Lists recent bills for reprint, review, or void workflows.",
    reads: ["Bill", "User"],
    writes: [],
    risk: "medium",
  },
  {
    id: "pos.bills.compute",
    domain: "pos",
    path: "/api/pos/bills/compute",
    file: "app/api/pos/bills/compute/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "POS billing",
    summary: "Prices a cart using canonical rates and returns split totals.",
    reads: [
      "InventorySession",
      "StockEntry",
      "ReceiptItem",
      "BillLine",
      "StockAdjustment",
      "ProductSize",
      "Product",
      "MiscItem",
      "ClearanceBatch",
    ],
    writes: [],
    risk: "medium",
  },
  {
    id: "pos.bills.commit",
    domain: "pos",
    path: "/api/pos/bills/commit",
    file: "app/api/pos/bills/commit/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "POS billing",
    summary: "Commits a bill with canonical pricing, payments, and audit trail.",
    reads: ["GallaDay", "InventorySession", "ProductSize", "Product", "MiscItem", "ClearanceBatch", "Setting"],
    writes: ["Bill", "BillLine", "PaymentAllocation", "AuditEvent", "ClearanceBatch", "Setting"],
    risk: "high",
  },
  {
    id: "pos.bills.open-tab",
    domain: "pos",
    path: "/api/pos/bills/open-tab",
    file: "app/api/pos/bills/open-tab/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "POS billing",
    summary: "Opens a customer tab with canonical pricing and audit trail.",
    reads: ["GallaDay", "InventorySession", "ProductSize", "Product", "MiscItem", "ClearanceBatch", "Setting"],
    writes: ["Bill", "BillLine", "AuditEvent", "ClearanceBatch", "Setting"],
    risk: "high",
  },
  {
    id: "pos.bills.settle-tab",
    domain: "pos",
    path: "/api/pos/bills/settle-tab",
    file: "app/api/pos/bills/settle-tab/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "POS billing",
    summary: "Settles a tab bill and records payment allocations.",
    reads: ["GallaDay", "InventorySession", "Bill"],
    writes: ["Bill", "PaymentAllocation", "AuditEvent"],
    risk: "high",
  },
  {
    id: "pos.bills.return",
    domain: "pos",
    path: "/api/pos/bills/return",
    file: "app/api/pos/bills/return/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "POS billing",
    summary: "Processes a return and records refund cash events.",
    reads: ["GallaDay", "InventorySession", "BillLine", "Setting"],
    writes: ["Bill", "BillLine", "AuditEvent", "GallaEvent", "Setting"],
    risk: "high",
  },
  {
    id: "indents.collection",
    domain: "indents",
    path: "/api/indents",
    file: "app/api/indents/route.ts",
    methods: ["GET"],
    auth: "admin",
    owner: "Supplier indents",
    summary: "Lists recent supplier indents with items and receipt references.",
    reads: ["Indent", "IndentItem", "SupplierReceipt"],
    writes: [],
    risk: "medium",
  },
  {
    id: "indents.item",
    domain: "indents",
    path: "/api/indents/[id]",
    file: "app/api/indents/[id]/route.ts",
    methods: ["GET"],
    auth: "admin",
    owner: "Supplier indents",
    summary: "Returns one indent with parsed items, mappings, and receipt details.",
    reads: ["Indent", "IndentItem", "ProductSize", "SupplierReceipt"],
    writes: [],
    risk: "medium",
  },
  {
    id: "indents.parse",
    domain: "indents",
    path: "/api/indents/parse",
    file: "app/api/indents/parse/route.ts",
    methods: ["POST"],
    auth: "admin",
    owner: "Supplier indents",
    summary: "Parses an uploaded KSBCL indent file into an indent and line items.",
    reads: ["Uploaded PDF or workbook", "ProductSize"],
    writes: ["Indent", "IndentItem"],
    risk: "high",
  },
  {
    id: "indents.confirm",
    domain: "indents",
    path: "/api/indents/[id]/confirm",
    file: "app/api/indents/[id]/confirm/route.ts",
    methods: ["POST"],
    auth: "admin",
    owner: "Supplier receipts",
    summary: "Confirms arrival for an indent and posts receipt stock movements.",
    reads: ["Indent", "IndentItem", "ProductSize", "StockLot"],
    writes: ["SupplierReceipt", "StockLot", "StockMovement"],
    risk: "high",
  },
  {
    id: "indents.map-item",
    domain: "indents",
    path: "/api/indents/[id]/map-item",
    file: "app/api/indents/[id]/map-item/route.ts",
    methods: ["POST"],
    auth: "admin",
    owner: "Supplier indents",
    summary: "Maps a parsed KSBCL indent item to a known product size.",
    reads: ["IndentItem", "ProductSize"],
    writes: ["IndentItem"],
    risk: "medium",
  },
  {
    id: "inventory.clearance",
    domain: "inventory",
    path: "/api/clearance",
    file: "app/api/clearance/route.ts",
    methods: ["GET", "POST"],
    auth: "session",
    owner: "Clearance inventory",
    summary: "Lists clearance batches or creates a discounted clearance batch.",
    reads: ["ClearanceBatch", "ProductSize"],
    writes: ["ClearanceBatch"],
    risk: "high",
  },
  {
    id: "inventory.clearance-cancel",
    domain: "inventory",
    path: "/api/clearance/[id]/cancel",
    file: "app/api/clearance/[id]/cancel/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "Clearance inventory",
    summary: "Cancels a clearance batch and stops discounted sale availability.",
    reads: ["ClearanceBatch"],
    writes: ["ClearanceBatch"],
    risk: "high",
  },
  {
    id: "inventory.physical-count",
    domain: "inventory",
    path: "/api/physical-count",
    file: "app/api/physical-count/route.ts",
    methods: ["GET", "POST"],
    auth: "admin",
    owner: "Physical count",
    summary: "Lists physical count sessions or creates a new count session with counted lines.",
    reads: ["PhysicalCountSession", "PhysicalCountLine", "ProductSize"],
    writes: ["PhysicalCountSession", "PhysicalCountLine"],
    risk: "high",
  },
  {
    id: "inventory.physical-count-approve",
    domain: "inventory",
    path: "/api/physical-count/[id]/approve",
    file: "app/api/physical-count/[id]/approve/route.ts",
    methods: ["POST"],
    auth: "admin",
    owner: "Physical count",
    summary: "Approves a physical count session and posts adjustment movements.",
    reads: ["PhysicalCountSession", "PhysicalCountLine", "StockLot"],
    writes: ["PhysicalCountSession", "StockLot", "StockMovement"],
    risk: "high",
  },
  {
    id: "inventory.reconciliation",
    domain: "inventory",
    path: "/api/reconciliation",
    file: "app/api/reconciliation/route.ts",
    methods: ["GET", "PATCH"],
    auth: "admin",
    owner: "Inventory reconciliation",
    summary: "Lists reconciliation rows and lets admins approve or note variance decisions.",
    reads: ["ReconciliationRecord"],
    writes: ["ReconciliationRecord"],
    risk: "high",
  },
  {
    id: "inventory.sessions-current",
    domain: "inventory",
    path: "/api/inventory/sessions",
    file: "app/api/inventory/sessions/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "Inventory sessions",
    summary: "Ensures daily rollover, then returns the current active inventory session for today and rollover status.",
    reads: ["InventorySession"],
    writes: [],
    risk: "low",
  },
  {
    id: "inventory.stock-live",
    domain: "inventory",
    path: "/api/inventory/stock",
    file: "app/api/inventory/stock/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "Inventory stock",
    summary: "Returns live computed stock for all product sizes within the current session.",
    reads: ["ProductSize", "InventorySession", "StockEntry", "Receipt", "Bill", "StockAdjustment"],
    writes: [],
    risk: "low",
  },
  {
    id: "inventory.opening-bootstrap",
    domain: "inventory",
    path: "/api/inventory/opening",
    file: "app/api/inventory/opening/route.ts",
    methods: ["GET", "POST", "PATCH"],
    auth: "session",
    owner: "Inventory opening",
    summary: "Returns opening stock for a session, sets day-one opening stock, or updates the active session's opening balance.",
    reads: ["InventorySession", "ProductSize", "StockEntry"],
    writes: ["InventorySession", "StockEntry"],
    risk: "high",
    notes: "GET is session-readable for cashiers; POST and PATCH enforce admin-only mutation rules in the handler.",
  },
  {
    id: "attendance.logs",
    domain: "attendance",
    path: "/api/attendance",
    file: "app/api/attendance/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "Attendance",
    summary: "Returns attendance logs for a selected business date.",
    reads: ["AttendanceLog", "Staff"],
    writes: [],
    risk: "medium",
  },
  {
    id: "attendance.punch",
    domain: "attendance",
    path: "/api/attendance/punch",
    file: "app/api/attendance/punch/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "Attendance",
    summary: "Records explicit check-in or check-out events from face-matched or admin-manual flows.",
    reads: ["Staff", "AttendanceEvent"],
    writes: ["AttendanceEvent"],
    risk: "high",
    notes: "Manual overrides require admin auth. The request body now carries the target action so the kiosk can enforce one check-in and one check-out per day.",
  },
  {
    id: "attendance.metrics",
    domain: "attendance",
    path: "/api/attendance/metrics",
    file: "app/api/attendance/metrics/route.ts",
    methods: ["GET"],
    auth: "admin",
    owner: "Attendance",
    summary: "Returns attendance metrics for a month and optional staff filter.",
    reads: ["AttendanceLog", "Staff"],
    writes: [],
    risk: "medium",
  },
  {
    id: "face.enroll",
    domain: "attendance",
    path: "/api/face/enroll",
    file: "app/api/face/enroll/route.ts",
    methods: ["POST"],
    auth: "admin",
    owner: "Face attendance",
    summary: "Stores face descriptor samples for a staff member.",
    reads: ["Staff", "FaceProfile"],
    writes: ["FaceProfile", "FaceSample"],
    risk: "high",
  },
  {
    id: "face.profiles",
    domain: "attendance",
    path: "/api/face/profiles",
    file: "app/api/face/profiles/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "Face attendance",
    summary: "Returns enrolled face descriptors for local browser-side matching.",
    reads: ["FaceProfile", "FaceSample", "Staff"],
    writes: [],
    risk: "high",
    notes: "Treat returned descriptors as sensitive biometric data.",
  },
  {
    id: "staff.collection",
    domain: "staff",
    path: "/api/staff",
    file: "app/api/staff/route.ts",
    methods: ["GET", "POST"],
    auth: "session",
    owner: "Staff",
    summary: "Lists active staff with performance metrics, or creates a new staff member.",
    reads: ["Staff", "Bill", "AttendanceLog"],
    writes: ["Staff", "Clerk"],
    risk: "medium",
  },
  {
    id: "staff.metrics",
    domain: "staff",
    path: "/api/staff/metrics",
    file: "app/api/staff/metrics/route.ts",
    methods: ["GET"],
    auth: "admin",
    owner: "Staff analytics",
    summary: "Returns staff performance metrics for a date range.",
    reads: ["Staff", "Bill", "AttendanceLog"],
    writes: [],
    risk: "medium",
  },
  {
    id: "staff.payroll",
    domain: "staff",
    path: "/api/staff/payroll",
    file: "app/api/staff/payroll/route.ts",
    methods: ["GET"],
    auth: "admin",
    owner: "Staff analytics",
    summary: "Returns payroll reporting totals for a month and optional staff filter.",
    reads: ["AttendanceLog", "Staff", "Bill"],
    writes: [],
    risk: "medium",
  },
  {
    id: "clerks.collection",
    domain: "staff",
    path: "/api/clerks",
    file: "app/api/clerks/route.ts",
    methods: ["GET", "POST"],
    auth: "session",
    owner: "Clerks",
    summary: "Lists active clerks or creates a new clerk for POS attribution.",
    reads: ["Clerk"],
    writes: ["Clerk"],
    risk: "medium",
  },
  {
    id: "notifications.collection",
    domain: "notifications",
    path: "/api/notifications",
    file: "app/api/notifications/route.ts",
    methods: ["GET"],
    auth: "session",
    owner: "Alerts",
    summary: "Lists active user-visible notifications and operational alerts.",
    reads: ["Alert"],
    writes: [],
    risk: "medium",
  },
  {
    id: "notifications.dismiss",
    domain: "notifications",
    path: "/api/notifications/[id]/dismiss",
    file: "app/api/notifications/[id]/dismiss/route.ts",
    methods: ["POST"],
    auth: "session",
    owner: "Alerts",
    summary: "Dismisses a notification for the current workflow.",
    reads: ["Alert"],
    writes: ["Alert"],
    risk: "low",
  },
  {
    id: "cron.rollover",
    domain: "cron",
    path: "/api/cron/rollover",
    file: "app/api/cron/rollover/route.ts",
    methods: ["POST"],
    auth: "cron-secret",
    owner: "Daily automation",
    summary: "Runs the daily rollover job guarded by CRON_SECRET.",
    reads: ["BusinessDay", "StockLot", "ReconciliationRecord"],
    writes: ["BusinessDay", "StockLot", "ReconciliationRecord"],
    risk: "high",
  },
  {
    id: "cron.eod",
    domain: "cron",
    path: "/api/cron/eod",
    file: "app/api/cron/eod/route.ts",
    methods: ["POST"],
    auth: "cron-secret",
    owner: "Daily automation",
    summary: "Runs end-of-day processing for the previous business date.",
    reads: ["Bill", "GallaDay", "StockLot", "ReconciliationRecord"],
    writes: ["DailySummary", "ReconciliationRecord", "Alert"],
    risk: "high",
  },
  {
    id: "settings.collection",
    domain: "pos",
    path: "/api/settings",
    file: "app/api/settings/route.ts",
    methods: ["GET", "POST"],
    auth: "session",
    owner: "Settings",
    summary: "Returns or updates global system settings and operational thresholds.",
    reads: ["Setting"],
    writes: ["Setting"],
    risk: "medium",
  },
  {
    id: "staff.item",
    domain: "staff",
    path: "/api/staff/[id]",
    file: "app/api/staff/[id]/route.ts",
    methods: ["GET", "PUT", "DELETE"],
    auth: "admin",
    owner: "Staff",
    summary: "Returns, updates, or soft-deletes a staff member.",
    reads: ["Staff"],
    writes: ["Staff"],
    risk: "medium",
  },
] as const satisfies readonly ApiRouteDefinition[]

export type ApiRouteId = (typeof API_ROUTES)[number]["id"]

export const API_ROUTE_BY_ID = Object.fromEntries(
  API_ROUTES.map((route) => [route.id, route]),
) as Record<ApiRouteId, (typeof API_ROUTES)[number]>

export const API_ROUTE_BY_PATH = Object.fromEntries(
  API_ROUTES.map((route) => [route.path, route]),
) as Record<(typeof API_ROUTES)[number]["path"], (typeof API_ROUTES)[number]>

export function getApiRoutesByDomain(domain: ApiDomain): ApiRouteDefinition[] {
  return API_ROUTES.filter((route) => route.domain === domain)
}
